//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using NHibernate.Cfg.MappingSchema;
using NHibernate.Mapping.ByCode;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH3114
{
	using System.Threading.Tasks;
	[TestFixture]
	public class ImplicitByCodeFixtureAsync : TestCaseMappingByCode
	{
		protected override HbmMapping GetMappings()
		{
			var mapper = new ModelMapper();
			mapper.Class<Entity>(rc =>
			{
				rc.Id(i => i.Id, m => m.Generator(Generators.GuidComb));
				rc.Component(p => p.FirstComponent,
					m =>
					{
						m.Set(c => c.ComponentCollection,
							// table name omitted, expecting a reasonable default
							c => { },
							c => c.Element());
						// not specifying a column name here (and below) causes an insert failure during session.Flush
						m.Property(p => p.ComponentProperty);
					});
				rc.Component(p => p.SecondComponent,
					m =>
					{
						m.Set(c => c.ComponentCollection,
							// table name omitted, expecting a reasonable default
							c => { },
							c => c.Element());
						// not specifying a column name here (and above) causes an insert failure during session.Flush
						m.Property(p => p.ComponentProperty);
					});
			});

			return mapper.CompileMappingForAllExplicitlyAddedEntities();
		}

		protected override void OnTearDown()
		{
			using (ISession session = OpenSession())
			using (ITransaction transaction = session.BeginTransaction())
			{
				session.Delete("from Entity");

				session.Flush();
				transaction.Commit();
			}
		}

		[Test]
		public async Task Component_WithSameType_ButDifferentTables_IsStoredInTheCorrectTableAndCollectionAsync()
		{
			Guid previouslySavedId;
			using (var session = OpenSession())
			{
				var entity = new Entity();
				entity.FirstComponent = new Component();
				entity.FirstComponent.ComponentProperty = "First";
				entity.FirstComponent.ComponentCollection = new List<string> { "FirstOne", "FirstTwo", "FirstThree" };
				entity.SecondComponent = new Component();
				entity.SecondComponent.ComponentProperty = "Second";
				entity.SecondComponent.ComponentCollection = new List<string> { "SecondOne", "SecondTwo", "SecondThree" };
				await (session.SaveOrUpdateAsync(entity));
				// flushing fails due to ComponentProperty of both components being mapped to the same column,
				// as the AbstractEntityPersister expects 3 parameters but only gets 2.
				await (session.FlushAsync());
				previouslySavedId = entity.Id;
			}

			using (var session = OpenSession())
			{
				var entity = await (session.GetAsync<Entity>(previouslySavedId));
				Assert.IsNotNull(entity);
				Assert.IsNotNull(entity.FirstComponent);
				Assert.AreEqual("First", entity.FirstComponent.ComponentProperty);
				CollectionAssert.AreEquivalent(new[] { "FirstOne", "FirstTwo", "FirstThree" }, entity.FirstComponent.ComponentCollection);
				Assert.IsNotNull(entity.SecondComponent);
				Assert.AreEqual("Second", entity.SecondComponent.ComponentProperty);
				CollectionAssert.AreEquivalent(new[] { "SecondOne", "SecondTwo", "SecondThree" }, entity.SecondComponent.ComponentCollection);
			}
		}
	}
}
